import { TEAL_TEXT } from "../../lib/data";

/* Couleurs d'accent des articles (identiques à celles de la page Conseils) */
const PINK   = "#D4197A";
const GREEN  = "#10B981";
const AMBER  = "#F59E0B";
const PURPLE = "#8B5CF6";

/* ── Articles conseils ──
   `seoTitle` : version courte du titre pour la balise <title> (titre + " | J'MTD" < 60 caractères) */
export const ARTICLES = [
  {
    id: 1, cat: "menage", icon: "menage",
    slug: "les-5-erreurs-menage",
    tag: "Ménage", color: TEAL_TEXT,
    title: "Les 5 erreurs que tout le monde fait en faisant le ménage",
    seoTitle: "Les 5 erreurs les plus courantes en ménage",
    desc: "Commencer par les sols avant les surfaces, oublier les interrupteurs, utiliser trop de produit… On vous explique comment éviter ces pièges pour un résultat impeccable en moins de temps.",
    duration: "3 min",
    tips: [
      "Toujours commencer par le haut (plafond, étagères) et finir par les sols",
      "Nettoyer les interrupteurs et poignées de porte — zones les plus touchées",
      "Moins de produit = meilleur résultat (réduit les résidus sur les surfaces)",
      "Laisser agir le produit 2 à 3 minutes avant d'essuyer",
      "Utiliser des chiffons microfibre plutôt que du papier essuie-tout",
    ],
  },
  {
    id: 2, cat: "rangement", icon: "rangement",
    slug: "methode-konmari",
    tag: "Rangement", color: PINK,
    title: "La méthode KonMari expliquée simplement",
    seoTitle: "La méthode KonMari expliquée simplement",
    desc: "Marie Kondo a révolutionné l'art du rangement. Découvrez comment appliquer sa méthode chez vous, pièce par pièce, pour ne garder que ce qui vous apporte de la joie.",
    duration: "5 min",
    tips: [
      "Trier par catégorie, pas par pièce (ex : tous les vêtements ensemble)",
      "Se poser la question : 'Est-ce que cet objet me procure de la joie ?'",
      "Ranger verticalement les vêtements pliés pour tout voir d'un coup",
      "Commencer par les vêtements, finir par les souvenirs (le plus difficile)",
      "Garder chaque objet à une place fixe — chaque chose a sa maison",
    ],
  },
  {
    id: 3, cat: "produits", icon: "sparkles",
    slug: "bicarbonate-vinaigre-blanc",
    tag: "Produits naturels", color: GREEN,
    title: "Bicarbonate + vinaigre blanc : le duo miracle pour votre maison",
    seoTitle: "Bicarbonate + vinaigre blanc : le duo malin",
    desc: "Ces deux ingrédients du placard remplacent des dizaines de produits chimiques coûteux. On vous dévoile toutes les astuces et les dosages exacts pour chaque surface.",
    duration: "4 min",
    tips: [
      "Bicarbonate seul : dégraisse, désodorise, nettoie l'évier et les casseroles",
      "Vinaigre blanc : détartre robinets, douche, machine à laver (bac assouplissant)",
      "Ne pas mélanger les deux ensemble — ils s'annulent (CO₂ neutre)",
      "Citron + gros sel : nettoie les planches à découper en bois",
      "Bicarbonate dans le bac réfrigérateur : absorbe les mauvaises odeurs",
    ],
  },
  {
    id: 4, cat: "temps", icon: "clock",
    slug: "menage-express-30-minutes",
    tag: "Gain de temps", color: AMBER,
    title: "Le ménage express : faites le tour de votre maison en 30 minutes",
    seoTitle: "Ménage express : toute la maison en 30 min",
    desc: "Une routine en 7 étapes chronométrées pour avoir un intérieur propre et présentable rapidement. Idéal pour les visites impromptues ou les semaines chargées.",
    duration: "3 min",
    tips: [
      "5 min : ramasser et ranger ce qui traîne dans toutes les pièces",
      "5 min : nettoyer les surfaces visibles (tables, plan de travail, évier)",
      "5 min : nettoyer les toilettes et lavabo",
      "5 min : passer l'aspirateur dans les pièces principales",
      "5 min : essuyer les miroirs et vitres en façade + vider poubelles",
      "5 min : passer la serpillière cuisine et salle de bain",
    ],
  },
  {
    id: 5, cat: "comparatifs", icon: "search",
    slug: "aspirateur-balai-ou-robot",
    tag: "Comparatif", color: PURPLE,
    title: "Aspirateur balai vs aspirateur robot : lequel choisir en Martinique ?",
    seoTitle: "Aspirateur balai ou robot : lequel choisir ?",
    desc: "Humidité, poils d'animaux, sol en carrelage ou parquet… On passe en revue les critères spécifiques à nos intérieurs antillais pour vous aider à choisir le bon appareil.",
    duration: "6 min",
    tips: [
      "Robot : idéal pour l'entretien quotidien sans effort (programme automatique)",
      "Balai : indispensable pour les coins, les bords et le nettoyage en profondeur",
      "En Martinique : l'humidité abîme les capteurs des robots bas de gamme — misez sur une marque reconnue",
      "Poils d'animaux : préférez un balai avec brosse anti-poils intégrée",
      "Solution idéale : un robot pour le quotidien + un balai pour le hebdomadaire",
    ],
  },
  {
    id: 6, cat: "rangement", icon: "rangement",
    slug: "organiser-placards-cuisine",
    tag: "Rangement", color: PINK,
    title: "Organiser ses placards de cuisine : les secrets des pros",
    seoTitle: "Organiser ses placards de cuisine",
    desc: "Zones de travail, rangement vertical, étiquetage, boîtes hermétiques… Adoptez les techniques des cuisines professionnelles pour ne plus rien chercher.",
    duration: "4 min",
    tips: [
      "Créer 3 zones : préparation (plan de travail), cuisson (près de la gazinière), vaisselle (près de l'évier)",
      "Ranger les épices verticalement avec étiquettes lisibles sur le dessus",
      "Boîtes hermétiques uniformes : gain de place énorme dans les placards",
      "Tiroir à fond de tiroir : poser le couvercle à côté de la boîte (pas empilé)",
      "Ce que vous utilisez le plus → hauteur des yeux ou des mains",
    ],
  },
  {
    id: 7, cat: "produits", icon: "sparkles",
    slug: "produits-menagers-indispensables",
    tag: "Produits", color: GREEN,
    title: "Les 6 produits ménagers indispensables (et les 10 inutiles)",
    seoTitle: "Les 6 produits ménagers indispensables",
    desc: "Le marketing nous pousse à acheter des dizaines de produits spécialisés. En réalité, 6 produits suffisent à nettoyer toute votre maison. On fait le tri ensemble.",
    duration: "5 min",
    tips: [
      "✅ Les 6 essentiels : liquide vaisselle, bicarbonate, vinaigre blanc, savon de Marseille, alcool ménager, eau de Javel diluée",
      "❌ Inutile : produit spécial salle de bain, spray vitres, nettoyant WC (le vinaigre fait tout)",
      "❌ Inutile : lingettes désinfectantes individuelles (coûteuses et polluantes)",
      "Le liquide vaisselle dilué remplace 90% des nettoyants multi-surfaces",
      "Alcool ménager à 70° : désinfecte, nettoie les vitres, enlève les traces",
    ],
  },
  {
    id: 8, cat: "menage", icon: "menage",
    slug: "vitres-sans-traces",
    tag: "Ménage", color: TEAL_TEXT,
    title: "Vitres sans traces : la technique que les professionnels utilisent",
    seoTitle: "Vitres sans traces : la technique des pros",
    desc: "Eau démagnétisée, microfibres, mouvement en Z, bon timing selon la chaleur… La méthode complète pour des vitres parfaitement transparentes, même sous le soleil antillais.",
    duration: "3 min",
    tips: [
      "Ne jamais nettoyer en plein soleil (sèche trop vite et laisse des traces)",
      "Mouvement en S ou en Z de haut en bas — jamais de cercles",
      "Deux chiffons : un humide pour nettoyer, un sec pour polir",
      "Eau + une goutte de liquide vaisselle : solution parfaite et économique",
      "Journaux froissés : alternative efficace aux chiffons pour un fini brillant",
    ],
  },
  {
    id: 9, cat: "temps", icon: "calendar",
    slug: "planning-menager-hebdomadaire",
    tag: "Organisation", color: AMBER,
    title: "Créez un planning ménager hebdomadaire qui fonctionne vraiment",
    seoTitle: "Planning ménager hebdomadaire qui marche",
    desc: "Finissez avec le ménage du samedi en bloc ! Répartissez les tâches sur la semaine selon une logique intelligente et gagnez vos week-ends.",
    duration: "4 min",
    tips: [
      "Lundi : cuisine (surfaces, évier, sol) — 15 min",
      "Mardi : salle de bain + WC — 15 min",
      "Mercredi : dépoussiérer salon + chambre — 15 min",
      "Jeudi : aspiration de toute la maison — 20 min",
      "Vendredi : sols + linge — 20 min + machine",
      "Week-end : libre ou grand ménage mensuel si nécessaire",
    ],
  },
  {
    id: 10, cat: "comparatifs", icon: "search",
    slug: "serpilliere-microfibre-ou-vapeur",
    tag: "Comparatif", color: PURPLE,
    title: "Serpillière classique, microfibre ou vapeur : le comparatif honnête",
    seoTitle: "Serpillière, microfibre ou vapeur ?",
    desc: "Test, efficacité, coût, entretien… On compare les 3 méthodes de lavage des sols pour vous dire laquelle vaut vraiment l'investissement selon votre type de sol.",
    duration: "5 min",
    tips: [
      "Serpillière classique : efficace mais difficile à essorer + sèche lentement (moisissures en zone humide)",
      "Microfibre plate : légère, sèche vite, lave à 60°C, idéale pour carrelage Martinique",
      "Vapeur : désinfecte sans produit chimique, parfaite pour allergiques — coût initial plus élevé",
      "Notre recommandation Martinique : microfibre plate pour quotidien + vapeur mensuel",
      "Éviter : le seau unique (repose les saletés) — utiliser deux seaux eau propre / eau sale",
    ],
  },
  {
    id: 11, cat: "rangement", icon: "rangement",
    slug: "desencombrer-sa-chambre",
    tag: "Rangement", color: PINK,
    title: "Désencombrer sa chambre en une heure : le guide étape par étape",
    seoTitle: "Désencombrer sa chambre en une heure",
    desc: "Garde-robe, tables de nuit, sous le lit… Une checklist actionnable pour vider, trier et réorganiser votre chambre dans le bon ordre, sans vous épuiser.",
    duration: "6 min",
    tips: [
      "Commencer par vider complètement le dessus des meubles (tables de nuit, commode)",
      "Sous le lit : tout sortir, trier par catégorie, ne remettre que ce qui est utile",
      "Garde-robe : méthode des 3 piles (garder / donner / jeter) en 30 secondes par vêtement",
      "Règle : si vous ne l'avez pas porté depuis 12 mois en Martinique, c'est non",
      "Finir par ranger l'électronique (câbles, chargeurs) dans une boîte dédiée",
    ],
  },
  {
    id: 12, cat: "produits", icon: "jardinage",
    slug: "huiles-essentielles-menage",
    tag: "Produits naturels", color: GREEN,
    title: "Huiles essentielles et ménage : lesquelles utiliser et comment ?",
    seoTitle: "Huiles essentielles et ménage : le guide",
    desc: "Tea tree, lavande, eucalyptus, citron… Ces huiles naturelles ont des propriétés antibactériennes puissantes. On vous explique comment les intégrer à votre routine.",
    duration: "4 min",
    tips: [
      "Tea tree (arbre à thé) : antibactérien puissant — 10 gouttes dans l'eau de lavage des sols",
      "Lavande : désodorisante et antiseptique — quelques gouttes sur le filtre de l'aspirateur",
      "Citron : dégraissant naturel + odeur fraîche — dans le produit vaisselle",
      "Eucalyptus : anti-acariens — 5 gouttes dans la lessive pour literie",
      "⚠️ Toujours diluer les HE — ne jamais utiliser pures sur les surfaces",
    ],
  },
];

export function getArticleBySlug(slug) {
  return ARTICLES.find(a => a.slug === slug);
}
